# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
# Credit Fractalyse (CuBe)
#
version:                2.1
jobs:
  build:
    docker:
      - image:          circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: "Compile"
          command:
            make geth
  prerelease:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: "Compile"
          command: make geth
      - run:
          name: "Make tar PreRelease and publish"
          command: |
            cd build/bin
            VERSION=$(./geth version | grep "^Version:" | cut -d' ' -f2 | cut -d'-' -f1)
            echo $VERSION	  
            tar -cvjf etho-linux-V${VERSION}-test.tar.gz geth && rm geth
            go get github.com/tcnksm/ghr
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete -n "${CIRCLE_BRANCH}" -b "***FOR TESTING PURPOSE ONLY***" --prerelease "V${VERSION}-test" ./

  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: "Make tar Release and publish"
          command: |
            make geth
            cd build/bin
            VERSION=$(./geth version | grep "^Version:" | cut -d' ' -f2 | cut -d'-' -f1)
            echo $VERSION	  
            tar -cvjf etho-linux-V${VERSION}.tar.gz geth && rm geth
            go get github.com/tcnksm/ghr
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete "V${VERSION}" ./

workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - testnet-implementation
                - master
                - fix-circleci-builds
      - prerelease:
          filters:
            branches:
              only:
                - testnet-implementation
                - fix-circleci-builds
      - release:
          filters:
            branches:
              only:
                - master
